"""Training helpers: soft labels, combined losses, example sorting, evaluation."""

from .soft_labels import (
    LABEL_MODE_HARD_ONLY,
    LABEL_MODE_HARD_SOFT_AUX,
    LABEL_MODE_SOFT_PRIMARY,
    SoftLabelTable,
    build_soft_targets_for_window,
    dense_frame_labels_from_session,
    write_soft_labels_sidecar,
)
from .losses import compile_with_label_mode, make_label_loss
from .example_sort import (
    parse_labgym_example_basename,
    sort_examples_from_annotations,
    sort_examples_from_csv_subject_aware,
)
from .ethogram_examples import (
    GenerationConfig,
    collect_windows,
    generate_examples_from_ethogram,
    sample_windows_from_bout,
)
from .evaluation import (
    EvaluationMetrics,
    EvaluationRunInfo,
    ExamplePrediction,
    HighLossExample,
    compute_evaluation_metrics,
    format_taxonomy_drift_message,
    hard_labels_from_targets,
    high_loss_from_predictions,
    list_evaluation_runs,
    load_evaluation_run,
    model_classnames_from_parameters,
    model_settings_from_parameters_df,
    per_example_cross_entropy,
    predictions_from_model_output,
    rank_high_loss_examples,
    store_behavior_categories,
    taxonomy_drift,
    write_evaluation_run,
)
from .dataset_manifest import (
    MANIFEST_FILENAME,
    SCHEMA_VERSION,
    SPLIT_SEALED_TEST,
    SPLIT_TRAIN,
    SPLIT_UNASSIGNED,
    SPLIT_VALIDATION,
    DatasetManifest,
    EffectiveExample,
    ExampleRecord,
    example_id_from_path,
    filter_paths_by_manifest,
    resolve_train_val_paths,
    scan_example_store,
)

__all__ = [
    "LABEL_MODE_HARD_ONLY",
    "LABEL_MODE_HARD_SOFT_AUX",
    "LABEL_MODE_SOFT_PRIMARY",
    "SoftLabelTable",
    "build_soft_targets_for_window",
    "dense_frame_labels_from_session",
    "write_soft_labels_sidecar",
    "compile_with_label_mode",
    "make_label_loss",
    "parse_labgym_example_basename",
    "sort_examples_from_annotations",
    "sort_examples_from_csv_subject_aware",
    "GenerationConfig",
    "collect_windows",
    "generate_examples_from_ethogram",
    "sample_windows_from_bout",
    "EvaluationMetrics",
    "EvaluationRunInfo",
    "ExamplePrediction",
    "HighLossExample",
    "compute_evaluation_metrics",
    "format_taxonomy_drift_message",
    "hard_labels_from_targets",
    "high_loss_from_predictions",
    "list_evaluation_runs",
    "load_evaluation_run",
    "model_classnames_from_parameters",
    "model_settings_from_parameters_df",
    "per_example_cross_entropy",
    "predictions_from_model_output",
    "rank_high_loss_examples",
    "store_behavior_categories",
    "taxonomy_drift",
    "write_evaluation_run",
    "MANIFEST_FILENAME",
    "SCHEMA_VERSION",
    "SPLIT_SEALED_TEST",
    "SPLIT_TRAIN",
    "SPLIT_UNASSIGNED",
    "SPLIT_VALIDATION",
    "DatasetManifest",
    "EffectiveExample",
    "ExampleRecord",
    "example_id_from_path",
    "filter_paths_by_manifest",
    "resolve_train_val_paths",
    "scan_example_store",
]
